language: php
php:
   - '5.6'
   - '7.0'
   - '7.1'
   - '7.2'
   - '7.3'
install:
   - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install -vvv
script:
   - ./vendor/bin/phpcs
   - ./vendor/bin/phpunit
